defaults: &defaults
  working_directory: ~/icons
  docker:
    - image: circleci/node:lts

version: 2
jobs:
  dependencies:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: yarn install --frozen-lockfile --ignore-engines
      - persist_to_workspace:
          root: .
          paths:
            - '*'
  test:
    <<: *defaults
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Test
          command: yarn test
  build:
    <<: *defaults
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Build
          command: yarn build
      - persist_to_workspace:
          root: .
          paths:
            - '*'
  demo:
    <<: *defaults
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Build Demo page
          command: yarn demo:build
      - run:
          name: Deploy Demo page to Github pages
          command: |
            mkdir ~/.ssh
            ssh-keyscan github.com >> ~/.ssh/known_hosts
            git config --global user.email "circleci@transferwise.com"
            git config --global user.name "CircleCI"
            yarn demo:deploy
  release:
    <<: *defaults
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Release to GitHub
          command: |
            mkdir ~/.ssh
            ssh-keyscan github.com >> ~/.ssh/known_hosts
            yarn release-to-github

  publish:
    <<: *defaults
    steps:
      - run:
          name: Setup npm token
          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN_PUBLISH" >> ~/.npmrc
      - attach_workspace:
          at: .
      - run:
          name: Publish on npm
          command: npm publish --access=public

workflows:
  version: 2
  install-test-build-publish-release:
    jobs:
      - dependencies:
          filters:
            branches:
              ignore: gh-pages
      - test:
          requires:
            - dependencies
      - build:
          requires:
            - test
            - dependencies
      - publish:
          context: frontend-publish
          requires:
            - test
            - build
          filters:
            branches:
              only: master
      - release:
          context: frontend-publish
          requires:
            - test
            - build
          filters:
            branches:
              only: master
      - demo:
          context: frontend-publish
          requires:
            - build