defaults: &defaults
  working_directory: ~/icons
  docker:
    - image: circleci/node:lts

version: 2
jobs:
  dependencies:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: yarn install --frozen-lockfile --ignore-engines
      - persist_to_workspace:
          root: .
          paths:
            - '*'
  test:
    <<: *defaults
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Test
          command: yarn test

  build:
    <<: *defaults
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Build
          command: yarn build
      - persist_to_workspace:
          root: .
          paths:
            - '*'

  release:
    <<: *defaults
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Release to GitHub
          command: |
            mkdir ~/.ssh
            ssh-keyscan github.com >> ~/.ssh/known_hosts
            yarn run release-to-github

  publish-prerelease:
    <<: *defaults
    steps:
      - run:
          name: Setup npm token
          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN_PUBLISH" >> ~/.npmrc
      - attach_workspace:
          at: .
      - run:
          name: Publish prerelease version on npm with beta tag
          command: npm publish --tag beta

  publish:
    <<: *defaults
    steps:
      - run:
          name: Setup npm token
          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN_PUBLISH" >> ~/.npmrc
      - attach_workspace:
          at: .
      - run:
          name: Publish on npm
          command: npm publish --access=public

workflows:
  version: 2
  deps-test-build-publish-release:
    jobs:
      - dependencies:
          filters:
            branches:
              ignore: gh-pages
      - test:
          requires:
            - dependencies
      - build:
          requires:
            - test
            - dependencies
      - publish-prerelease:
        context: frontend-publish
        requires:
          - test
          - build
        filters:
          branches:
            only: beta
      - publish:
          context: frontend-publish
          requires:
            - test
            - build
          filters:
            branches:
              only: master
      - release:
        context: frontend-publish
        requires:
          - test
          - build
        filters:
          branches:
            only: master